version: "2.3"

services:
  backend:
    build:
      context: ./
      target: backend
    environment:
      - SPRING_REDIS_HOST=redis
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./
      target: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  redis:
    image: "redis"
    ports:
      - '6379:6379'
